
server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/book?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.meeting2.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true
      use-generated-keys: true

